Add "Wuhu Island" by tizona and Maxmos
Warzone/PublicMaps pull request #57
Opened 2022-03-27 02:43 UTC by TheRealPear

### Map Name
Wuhu Island

### Gamemode(s)
King of the Hill

### Description & Team Sizes
This is the ported version of Wuhu Island from the original [TGM maps](https://github.com/WarzoneMC/tgm-maps) repo. The map is inspired by the Nintendo Wii Sport game series. It has 4 teams with minimum of 3 players each and maximum of 100 players.

### Screenshots
(will complete later)

### XML
https://github.com/TheRealPear/PublicMaps/blob/wuhu-island/KoTH/Standard/Wuhu%20Island/map.xml

### Map Download
https://github.com/TheRealPear/PublicMaps/tree/wuhu-island/KoTH/Standard/Wuhu%20Island

---

### Map Checklist
>To mark as completed, replace the space between the [ ] with an `X` or click on the checkbox after submitting this pull request.
- [X] Contains a `map.xml` file with valid syntax and formatting.
- [X] The `map.xml` uses proto `1.4.0` or above (older or legacy maps are exempt, so long as the XML works).
- [X] The `map.xml` explicitly [sets the gamemode](https://pgm.dev/docs/modules/general/main#map-gamemode) (for stat-tracking).
- [X] The `map.xml` has correctly credited the map authors and contributors.
- [X] Contains `map.png` file (`290x246`).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.

---

### Known Issues
- The spawn regions are placed in incorrect locations.
- The capture point's radius are off by one block, causing the hill to not change color on certain sides.

2022-03-27 02:49 UTC, TheRealPear commented
Another thing I've forgot to list is that I've slightly modified the map to reflect the actual name of locations from Wii games as well as adding slabs for uphill paths for easier navigation and better lighting (with time cycle enabled).

2022-03-27 22:14 UTC, Wesdial requested changes
- The spawn regions are placed in incorrect locations.

> Fixed, green's spawn region, was off by one block, allowing enemies to enter it.

- The capture point's radius are off by one block, causing the hill to not change color on certain sides.

> Fixed as well, Incorrect coordinates, off by a block. This should fix everything you have. (everything has been tested before proposing these changes. feel free to test them as well if you do so please.)

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="the-candle" base="-1372.5,32,476.5" radius="4" height="4"/>
`<cylinder id="the-candle" base="-1371.5,32,476.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="cabana-lagoon" base="-1295.5,31,321.5" radius="4" height="4"/>
`<cylinder id="cabana-lagoon" base="-1294.5,31,321.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="stillwater-grotto" base="-1278.5,25,388.5" radius="4" height="4"/>
`<cylinder id="stillwater-grotto" base="-1277.5,25,388.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="summer-castle" base="-1205.5,53,400.5" radius="4" height="4"/>
` <cylinder id="summer-castle" base="-1204.5,53,400.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="mysterious-ruins" base="-1146.5,30,269.5" radius="4" height="4"/>
`<cylinder id="mysterious-ruins" base="-1145.5,30,269.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="maka-wuhu" base="-1129.5,63,369.5" radius="4" height="4"/>
`<cylinder id="maka-wuhu" base="-1128.5,63, 369.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="cedar-tree-cave" base="-1120.5,45,422.5" radius="4" height="4"/>
` <cylinder id="cedar-tree-cave" base="-1119.5,45,422.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="cocoba-hotel" base="-1036.5,21,437.5" radius="4" height="4"/>
` <cylinder id="cocoba-hotel" base="-1035.5,21,437.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +            <cylinder id="nineteeth-hole-hotel" base="-1421.5,26,883.5" radius="4" height="4"/>
` <cylinder id="nineteeth-hole-hotel" base="-1420.5,26,883.5" radius="4" height="4"/>`

2022-03-27 22:14 UTC, Wesdial commented on KoTH/Standard/Wuhu Island/map.xml
> +        <cuboid id="green-spawn-protection" min="-1162,60,358" max="-1169,67,351"/>
`<cuboid id="green-spawn-protection" min="-1159.5,60,351.5" max="-1170.5,67,359.5"/>`

- Green's spawn region, appeared to be the only region that needed a fix, it was off by one block, and players could enter the spawn. This should fix it.

2022-03-28 21:58 UTC, TheRealPear commented
All map issues should be resolved.

As for the Speed I effect and Feather Falling I enchantment, I will leave that up to the map developers on keeping or removing it from this map. I personally think it would benefit from a boost as it is quite a large map compared to what we have in this repo.

2022-03-29 00:17 UTC, merged